/* Reusable graph explorer markup and styles, separate from state and requests. */
(function(global){
  'use strict';
  const e=global.PaymentPipelineUI.element;
  const css=`
    .gx-panel{margin-top:24px;scroll-margin-top:20px}.gx-panel .gx-heading{margin-bottom:18px}.gx-panel .gx-title{font-size:24px}.gx-panel .gx-controls{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.gx-panel .gx-filters{margin:16px 0}.gx-panel .gx-controls label{font-size:11px}.gx-panel .gx-summary{display:flex;gap:8px 22px;flex-wrap:wrap;margin:16px 0;font-size:12px}.gx-panel .gx-summary strong{font-weight:650}.gx-panel .gx-workspace{display:grid;grid-template-columns:minmax(0,1fr) 280px;border:1px solid var(--pl-line);border-radius:10px;overflow:hidden}.gx-panel .gx-stage{min-width:0;position:relative;background:var(--pl-wash)}.gx-panel .gx-canvas{height:580px;width:100%;touch-action:none}.gx-panel .gx-canvas canvas:focus-visible{outline:2px solid var(--pl-accent);outline-offset:-3px}.gx-panel .gx-tools{display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap;padding:10px;border-bottom:1px solid var(--pl-line);background:var(--pl-panel)}.gx-panel .gx-tools select{width:135px;height:32px;font-size:11px}.gx-panel .gx-tools button{padding:6px 10px}.gx-panel .gx-inline{display:flex;gap:6px;align-items:center;font-size:11px}.gx-panel .gx-side{border-left:1px solid var(--pl-line);padding:16px;min-width:0;max-height:710px;overflow:auto}.gx-panel .gx-side pre{max-height:240px;overflow:auto;font-size:11px;white-space:pre-wrap;overflow-wrap:anywhere}.gx-panel .gx-side .pl-facts{grid-template-columns:100px minmax(0,1fr);font-size:11px}.gx-panel .gx-search{display:flex;gap:6px;margin:10px 0}.gx-panel .gx-search input{height:34px}.gx-panel .gx-search button{padding:5px 10px}.gx-panel .gx-results{max-height:175px;overflow:auto;display:grid;gap:6px;margin-bottom:16px}.gx-panel .gx-results button{text-align:left;justify-content:flex-start;white-space:normal;overflow-wrap:anywhere}.gx-panel .gx-legend{padding:10px 12px;display:flex;flex-wrap:wrap;gap:6px 15px;border-top:1px solid var(--pl-line);font-size:11px}.gx-panel .gx-key{display:inline-flex;align-items:center;gap:5px}.gx-panel .gx-dot{width:9px;height:9px;border-radius:50%;display:inline-block}.gx-panel .gx-note{padding:10px 12px;border-top:1px solid var(--pl-line);font-size:11px;color:var(--pl-quiet)}.gx-panel .gx-browse{margin-top:18px}.gx-panel .gx-table{max-height:280px;overflow:auto}.gx-panel .gx-table th{position:sticky;top:0;background:var(--pl-panel);z-index:1}.gx-panel .gx-table button{max-width:240px;overflow-wrap:anywhere;white-space:normal}.gx-panel .gx-empty{position:absolute;inset:150px 25px auto;text-align:center;pointer-events:none;color:var(--pl-quiet)}.gx-panel [aria-pressed=true]{border-color:var(--pl-accent);color:var(--pl-accent)}.gx-panel .gx-inspector-title{overflow-wrap:anywhere}.gx-panel .gx-state{min-height:20px;margin:12px 0}.gx-panel .gx-filter-note{font-size:11px;color:var(--pl-quiet);margin-top:8px}
    @media(min-width:1600px){.gx-panel .gx-canvas{height:660px}}@media(max-width:900px){.gx-panel .gx-workspace{grid-template-columns:1fr}.gx-panel .gx-side{border-left:0;border-top:1px solid var(--pl-line);max-height:none}.gx-panel .gx-canvas{height:440px}.gx-panel .gx-controls{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){.gx-panel{padding:14px!important}.gx-panel .gx-canvas{height:360px}.gx-panel .gx-controls{gap:10px}.gx-panel .gx-tools{align-items:flex-start}}
  `;
  function installStyle(){if(document.getElementById('dataset-graph-style'))return;const style=e('style',document.head,css,{id:'dataset-graph-style'});return style;}
  function mount(panel,{prefix,closeId}){
    installStyle();
      const p=prefix;
      // The template is static. Dataset values enter via textContent only.
      panel.classList.add('gx-panel');
      panel.innerHTML=`
        <div class="pl-line gx-heading"><div><div class="pl-eyebrow">Explore relationships</div><h2 id="${p}-title" class="gx-title pl-gap">Dataset graph</h2></div><button id="${closeId}" type="button">Close graph</button></div>
        <p class="pl-muted pl-small">Start with a small time-ordered slice. Select an entity to inspect its properties and expand its connections.</p>
        <form id="${p}-filters" class="gx-filters">
          <div class="gx-controls">
            <label class="pl-field" for="${p}-node-limit">Visible entity limit<input id="${p}-node-limit" type="number" min="2" max="500" step="1" value="100" required></label>
            <label class="pl-field" for="${p}-edge-limit">Visible relationship limit<input id="${p}-edge-limit" type="number" min="1" max="2000" step="1" value="300" required></label>
            <label class="pl-field" for="${p}-direction">Expand direction<select id="${p}-direction"><option value="both">Both directions</option><option value="outgoing">Outgoing</option><option value="incoming">Incoming</option></select></label>
            <label class="pl-field" for="${p}-label">Relationship outcome<select id="${p}-label"><option value="">All outcomes</option><option value="1">Fraud</option><option value="0">Legitimate</option><option value="-1">Unknown</option></select></label>
            <label class="pl-field" for="${p}-start">From time (seconds, inclusive)<input id="${p}-start" type="number" step="any" placeholder="Beginning"></label>
            <label class="pl-field" for="${p}-stop">Until time (seconds, exclusive)<input id="${p}-stop" type="number" step="any" placeholder="End"></label>
            <label class="pl-field" for="${p}-edge-type">Relationship type<select id="${p}-edge-type"><option value="">All types</option></select></label>
            <div class="pl-field"><span>Load a fresh slice</span><button id="${p}-apply" class="pl-primary" type="submit">Apply filters & limits</button></div>
          </div>
          <p class="gx-filter-note">Limits apply to the whole visible graph, including expansions. Times use the dataset’s source clock. Applying filters starts a new view.</p>
        </form>
        <div class="pl-line"><div class="pl-actions"><button id="${p}-next" type="button" disabled>Next slice →</button><button id="${p}-undo" type="button" disabled>Undo exploration</button><button id="${p}-reset" type="button">Reset view</button></div><div class="pl-actions"><button id="${p}-cancel" type="button" hidden>Cancel loading</button><button id="${p}-export" type="button" disabled>Export visible JSON</button></div></div>
        <p id="${p}-status" class="gx-state pl-small pl-muted" role="status" aria-live="polite"></p><div id="${p}-error" class="pl-error" role="alert" hidden></div>
        <div id="${p}-summary" class="gx-summary"></div>
        <div class="gx-workspace">
          <div class="gx-stage"><div class="gx-tools"><div class="gx-inline"><label for="${p}-layout">Layout</label><select id="${p}-layout"><option value="force">Force-directed</option><option value="radial">Radial</option><option value="columns">By entity type</option></select><label class="gx-inline"><input id="${p}-labels" type="checkbox" checked> Labels</label></div><div class="gx-inline"><button id="${p}-zoom-out" type="button" aria-label="Zoom out">−</button><button id="${p}-zoom-in" type="button" aria-label="Zoom in">+</button><button id="${p}-fit" type="button">Fit graph</button></div></div><div id="${p}-canvas" class="gx-canvas"></div><p id="${p}-empty" class="gx-empty" hidden>No relationships match these filters. Try a wider time range or another outcome.</p><div id="${p}-legend" class="gx-legend"></div><p class="gx-note">Drag to pan or move entities · Scroll to zoom · Double-click an entity to expand · Arrowheads show direction. Use the tables below for keyboard access.</p></div>
          <aside class="gx-side" aria-label="Graph search and properties"><h3>Find an entity</h3><form id="${p}-search-form" class="gx-search"><input id="${p}-search" type="search" maxlength="200" aria-label="Search all dataset entities" placeholder="Search name or ID"><button id="${p}-search-button" type="submit">Search</button></form><p class="pl-muted pl-small">Searches the entire dataset, beyond this slice.</p><div id="${p}-search-results" class="gx-results pl-gap" aria-live="polite"></div><div id="${p}-inspect"><h3>Inspect the structure</h3><p class="pl-muted pl-small">Select an entity or relationship in the graph or tables below.</p></div><div class="pl-actions pl-gap"><button id="${p}-expand" type="button" disabled>Expand connections</button><button id="${p}-focus" type="button" disabled>Focus here</button></div><p class="pl-muted pl-small pl-gap">Degree counts describe the full dataset. Outcomes are recorded labels, not model predictions; unknown labels stay unknown.</p></aside>
        </div>
        <div class="gx-browse"><div class="pl-line"><div class="pl-actions"><button id="${p}-tabs-node" type="button" aria-pressed="true">Entities</button><button id="${p}-tabs-edge" type="button" aria-pressed="false">Relationships</button></div><div class="pl-actions"><span id="${p}-table-count" class="pl-small pl-muted"></span><button id="${p}-table-prev" type="button">Previous rows</button><button id="${p}-table-next" type="button">Next rows</button></div></div><div id="${p}-nodes" class="pl-table-wrap gx-table pl-gap"></div><div id="${p}-edges" class="pl-table-wrap gx-table pl-gap" hidden></div></div>`;
  }
  global.DatasetGraphView={mount};
})(globalThis);
