"""Reference logits, embeddings and gradients generated by the authors' code."""
import importlib.util
import json
from pathlib import Path
import sys
import unittest
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))


@unittest.skipUnless(importlib.util.find_spec("torch"), "optional PyTorch dependency")
class UpstreamParity(unittest.TestCase):
    def test_published_backbone_lte_trc_logits_and_gradients(self):
        import torch
        from framework.contracts import TemporalGraphDataset
        from framework.temporal_sampling import timestamp_groups
        from models.implementations.dyg_tami import Model

        with np.load(
            Path(__file__).with_name("upstream-oracle.npz"), allow_pickle=False
        ) as reference:
            metadata = json.loads(str(reference["metadata"]))
            n = len(reference["times"])
            data = TemporalGraphDataset(
                tuple(map(str, range(n))),
                reference["times"],
                reference["sources"],
                reference["destinations"],
                ("", "1", "2", "3", "4"),
                reference["nodes"],
                reference["edges"],
                tuple("abcd"),
                tuple("ef"),
                {},
            )
            model = Model()
            model._initialize(data, metadata["parameters"])
            model.network.load_state_dict(
                {
                    key: torch.from_numpy(reference[key].copy())
                    for key in model.network.state_dict()
                }
            )
            model.network.eval()
            losses = []
            for group in timestamp_groups(data, np.arange(n)):
                source, destination = model.network[
                    0
                ].compute_src_dst_node_temporal_embeddings(
                    data.sources[group], data.destinations[group], data.times[group]
                )
                np.testing.assert_allclose(
                    source.detach().numpy(),
                    reference["source_embeddings"][group],
                    atol=2e-6,
                    rtol=2e-5,
                )
                np.testing.assert_allclose(
                    destination.detach().numpy(),
                    reference["destination_embeddings"][group],
                    atol=2e-6,
                    rtol=2e-5,
                )
                positive, negative, proposed = model.score_group(
                    data, group, np.full(len(group), 4)
                )
                np.testing.assert_allclose(
                    positive.detach().numpy(),
                    reference["positive"][group],
                    atol=2e-6,
                    rtol=2e-5,
                )
                np.testing.assert_allclose(
                    negative.detach().numpy(),
                    reference["negative"][group],
                    atol=2e-6,
                    rtol=2e-5,
                )
                losses.append(
                    torch.nn.functional.binary_cross_entropy_with_logits(
                        torch.cat([positive, negative]),
                        torch.cat(
                            [torch.ones_like(positive), torch.zeros_like(negative)]
                        ),
                    )
                )
                model._commit(data, group, proposed)
            torch.stack(losses).sum().backward()
            for name, parameter in model.network.named_parameters():
                self.assertIsNotNone(parameter.grad, name)
                np.testing.assert_allclose(
                    parameter.grad.numpy(),
                    reference["grad_" + name],
                    atol=2e-6,
                    rtol=2e-5,
                    err_msg=name,
                )


if __name__ == "__main__":
    unittest.main()
